version: '3'
services:
  client:
    image: nowgnas/agora:client
    container_name: client
    ports:
      - 3000:3000
    environment:
      REACT_APP_SERVER_BASE_URL: https://i8a705.p.ssafy.io/api
    networks:
      - AGORA
  backend:
    image: nowgnas/agora:backend
    container_name: backend
    ports:
      - 8081:8081
    environment:
      USE_PROFILE: q
      HOST_NAME: q
      SCHEMA: q
      USERNAME: q
      PASSWORD: q
      JWT_SECRET: q
      REDISHOST: q
      REDISPASS: q
      MEETING_HOST: q
      MEETING_SECRET: q
    networks:
      - AGORA
networks:
  AGORA:
    external:
      name: AGORA
