spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:tcp://localhost/~/agora
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

server:
  port: 8080