spring:
  config:
    activate:
      on-profile: local
  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      login-callback-url: http://localhost:8080/request/auth/login/google/callback
      join-callback-url: http://localhost:8080/request/auth/join/google/callback
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:tcp://localhost/~/agora
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

server:
  port: 8080