spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080

oauth:
  naver:
    get-code:
      url: https://nid.naver.com/oauth2.0/authorize?
      login:
        redirect-uri: http://localhost:8080/naver/auth/login
      join:
        redirect-uri: http://localhost:8080/naver/auth/join
      response-type: code
      state: state

    redirect:
      url: https://nid.naver.com/oauth2.0/token
      header: Content-type
      header-value: application/x-www-form-urlencoded;charset=utf-8
      grant-type: authorization_code
    get-info:
      url: https://openapi.naver.com/v1/nid/me
      header-type: Content-type
      header-value: application/x-www-form-urlencoded;charset=utf-8
      auth:
        header-type: Authorization
        header-value: "Bearer "