spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  OAuth2:
    kakao:
      url: https://kauth.kakao.com/oauth/authorize
      api-key: 9b71df2737d70ddadb6b15f8710ccda4
      login-url: http://localhost:8080/login/auth/kakao
      join-url: http://localhost:8080/kakao/login  #http://localhost:8080/join/auth/kakao
      token-url : https://kauth.kakao.com/oauth/token
      info-url : https://kapi.kakao.com/v2/user/me
  datasource:
    url: jdbc:h2:tcp://localhost/~/agora
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
server:
  port: 8080